#!/usr/bin/env bash

set -euo pipefail

readonly ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly FIXTURE_DIR="$ROOT_DIR/tests/fixtures/render"
readonly DOCUMENT_PATH="$ROOT_DIR/docs/render-fixtures.md"
readonly ASSET_DIR="$ROOT_DIR/docs/assets/render-fixtures"
readonly FREEZE_VERSION="v0.2.2"

temporary_dir="$(mktemp -d "${TMPDIR:-/tmp}/puu-render-fixtures.XXXXXX")"

readonly temporary_dir
readonly temporary_asset_dir="$temporary_dir/assets"
readonly temporary_document="$temporary_dir/render-fixtures.md"
readonly freeze_bin="$temporary_dir/bin/freeze"

mkdir -p "$temporary_asset_dir" "$(dirname "$freeze_bin")"

(
  cd "$ROOT_DIR"
  cargo build --locked
)

GOBIN="$(dirname "$freeze_bin")" \
  go install "github.com/charmbracelet/freeze@$FREEZE_VERSION"

cat >"$temporary_document" <<'EOF'
# Successful Fixture Output Catalog

<!-- This file is generated by scripts/generate-render-fixtures.sh. Do not edit it directly. -->

This catalog lists the input and CLI output for each successful fixture in `tests/fixtures/render`. The images are generated from colorized standard output with [Freeze](https://github.com/charmbracelet/freeze).

Cargo and Go are required to update the catalog. Run the following command from the repository root:

```sh
./scripts/generate-render-fixtures.sh
```

## Featured Example

The [`order-model`](#order-model) fixture is a representative, practical schema. It demonstrates the CLI's typical output without attempting to cover every supported keyword.

## Contents

EOF

for input_path in "$FIXTURE_DIR"/*.json; do
  fixture_name="$(basename "$input_path" .json)"
  printf -- '- [%s](#%s)\n' "$fixture_name" "$fixture_name" >>"$temporary_document"
done

for input_path in "$FIXTURE_DIR"/*.json; do
  fixture_name="$(basename "$input_path" .json)"
  image_name="$fixture_name.png"

  "$ROOT_DIR/target/debug/puu" --color=always "$input_path" \
    | "$freeze_bin" \
      --config "$ROOT_DIR/docs/freeze.json" \
      --output "$temporary_asset_dir/$image_name"

  {
    printf '\n## %s\n\n' "$fixture_name"
    printf '[Source](../tests/fixtures/render/%s.json)\n\n' "$fixture_name"
    printf '### Input\n\n```json\n'
    cat "$input_path"
    printf '```\n\n### Output\n\n'
    printf '![CLI output for %s](assets/render-fixtures/%s)\n' "$fixture_name" "$image_name"
  } >>"$temporary_document"
done

mkdir -p "$ASSET_DIR"
find "$ASSET_DIR" -type f -name '*.png' -delete
cp "$temporary_asset_dir"/*.png "$ASSET_DIR"/
mv "$temporary_document" "$DOCUMENT_PATH"
chmod 0644 "$ASSET_DIR"/*.png "$DOCUMENT_PATH"

printf 'Generated %s and %s images.\n' \
  "$DOCUMENT_PATH" \
  "$(find "$ASSET_DIR" -type f -name '*.png' | wc -l | tr -d ' ')"
